spring:
  h2:
    console:
      enabled: true
      path: /h2-console
# h2 db
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
  datasource:
    url: jdbc:mysql://localhost:3306/vmp
    username: root
    password: 123qwe
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update


jwt:
  token:
    header: Authorization
    issuer: vanmanager
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 1800000
